module.exports = [
  { id: 'r4', code: 'R4', name: 'Rete 4', tvgLogo: '189', tvgName: '', tvgId: '' },
  { id: 'c5', code: 'C5', name: 'Canale 5', tvgLogo: '187', tvgName: '', tvgId: '' },
  { id: 'i1', code: 'I1', name: 'Italia 1', tvgLogo: '188', tvgName: '', tvgId: '' },
  { id: 'i2', code: 'I2', name: 'Italia 2', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: '20', code: 'LB', name: '20 Mediaset', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'la5', code: 'KA', name: 'La5 ', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'iris', code: 'KI', name: 'Iris', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'focus', code: 'FU', name: 'Focus Mediaset', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'extra', code: 'KQ', name: 'Mediaset Extra', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'topc', code: 'LT', name: 'Top Crime', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'boing', code: 'KB', name: 'Boing', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'cartoon', code: 'LA', name: 'Cartoonito', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'tg24', code: 'KF', name: 'TgCome 24', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'r101', code: 'ER', name: 'Radio 101', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'virgin', code: 'EW', name: 'Virgin Radio', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'm4c', code: 'W1', name: 'm4c', tvgLogo: '', tvgName: '', tvgId: '' },
  { id: 'c34', code: 'B6', name: 'Canale 34', tvgLogo: '', tvgName: '', tvgId: '' },
]
